version: "3.9"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "567:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - WEBHOOK_URL=https://kyra-nondesignate-novelistically.ngrok-free.dev/
      - N8N_PORT=5678
    restart: unless-stopped

volumes:
  n8n_data:
